# Generated by Django 4.0.1 on 2022-02-04 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_tag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='Tags',
        ),
    ]
